# Inspired from https://github.com/5car1z/ansible-debian-provisioning
- name: "Update and (Re)Deploy Services"
  hosts: all
  gather_facts: yes

  vars_files:
    - vars/vars.yml

  vars:
    ansible_ssh_user: "{{ my_admin_user }}"

  pre_tasks:
    - name: "Clone or Update Git Repo"
      git: "repo={{ my_github_repo }} dest={{ my_git_home }} version={{ my_git_branch | default('master') }} clone=yes force=yes accept_hostkey=True"
      tags: update

    - name: copy DockerHub env file
      copy:
        src: ./../services/dockerhub/dockerhub.env
        dest: /home/{{ my_admin_user }}/git/services/dockerhub
        owner: "{{ my_admin_user }}"
        group: "{{ my_admin_user }}"
        mode: 0644
      tags: update

  tasks:
    - name: "home"
      shell: "cd {{ services_home }}/home && ./build.sh --no-cache && ./stop.sh && ./start.sh"
      tags: home

    - name: "dockerhub"
      shell: "cd {{ services_home }}/dockerhub && ./start.sh"
      tags: dockerhub

    - name: "pygeoapi_master"
      shell: "cd {{ services_home }}/pygeoapi_master && ./build.sh --no-cache && ./stop.sh && ./start.sh"
      tags: pygeoapi_master

    - name: "pygeoapi_stable"
      shell: "cd {{ services_home }}/pygeoapi_stable && ./stop.sh && ./start.sh"
      tags: pygeoapi_stable

    - name: "pygeoapi_cite"
      shell: "cd {{ services_home }}/pygeoapi_cite && ./build.sh --no-cache && ./stop.sh && ./start.sh"
      tags: pygeoapi_cite

    - name: "pygeoapi_covid-19"
      shell: "cd {{ services_home }}/pygeoapi_covid-19 && ./build.sh --no-cache && ./stop.sh && ./start.sh"
      tags: pygeoapi_covid-19

    - name: "traefik"
      shell: "cd {{ services_home }}/traefik && ./start.sh"
      tags: traefik
