# Installs from Ansible galaxy
- src: sansible.users_and_groups
  version: v2.0.5

- src: oefenweb.postfix
  version: v2.7.0

- src: geerlingguy.pip
  version: 1.3.0

- src: geerlingguy.docker
  version: 2.5.2

# from GitHub
- src: https://github.com/justb4/ansible-ubuntu-base
  name: justb4.ubuntu-base
  version: v1.2

- src: https://github.com/justb4/ansible-ubuntu-ntp
  name: justb4.ubuntu-ntp
  version: v1.0

# Other examples
# from GitHub, overriding the name and specifying a specific tag
#- src: https://github.com/bennojoy/nginx
#  version: master
#  name: nginx_role
#
## from a webserver, where the role is packaged in a tar.gz
#- src: https://some.webserver.example.com/files/master.tar.gz
#  name: http-role
#
## from Bitbucket
#- src: git+https://bitbucket.org/willthames/git-ansible-galaxy
#  version: v1.4
#
## from Bitbucket, alternative syntax and caveats
#- src: https://bitbucket.org/willthames/hg-ansible-galaxy
#  scm: hg
#
## from GitLab or other git-based scm, using git+ssh
#- src: git@gitlab.company.com:mygroup/ansible-base.git
#  scm: git
#  version: "0.1"  # quoted, so YAML doesn't parse this as a floating-point value
